### ISSUE TITLE
v1.0.1 无法重命名

### ISSUE THREAD

**Issue by uwang** [a1mersnow/drive-rename#5]
![image](https://github.com/a1mersnow/drive-rename/assets/9262286/d0fab3ac-c361-461a-b5dc-bc12bbca4021)

**Comment by a1mersnow** [comment]
如果刷新页面也没有的话，猜测可能是你的文件名后缀不在正常的视频格式列表中：
mp4,flv,f4v,webm,m4v,mov,cpk,dirac,3gp,3g2,rm,rmvb,wmv,avi,asf,mpg,mpeg,mpe,vob,mkv,ram,qt,fli,flc,mod,iso,ts
因为截图里面看不清你的文件名，麻烦把弹框关掉截一张看看。

**Comment by uwang** [comment]
![image](https://github.com/a1mersnow/drive-rename/assets/9262286/9c02ea4d-adeb-48a7-9aa2-efe10cbb00c7)

`S01E01.2024.2160p.HQ.WEB-DL.H265.60fps.AAC.mp4`

**Comment by uwang** [comment]
应该和文件名没太大关系。
我切到这个扩展之前的版本改过名字的文件夹，也是无法匹配到文件名

**Comment by uwang** [comment]
环境 macOS 
![image](https://github.com/a1mersnow/drive-rename/assets/9262286/be100bd8-e7d2-4ba0-aa21-328a04f62fa7)

**Comment by a1mersnow** [comment]
破案了，“来自分享”层级下的有问题……
紧急的话，你可以先临时移动一下，我会在下个版本修复。

**Comment by uwang** [comment]
不着急，谢谢
